/**
 * Telegram 贴纸名称到 file_id 的映射
 * @type {Record<string, string>}
 */
const stickerNameToFileId = {
	"After_Bath_Drying_Hair": "CAACAgUAAx0CeySiRQACgdJpMtOWw8VFL2L0vf-abcKevpvbtgAC0RsAAiNbmFXUhadgSHhqdDYE",
	'Aggressive_Study_Advice': 'CAACAgUAAx0CeySiRQACgdZpMtRQEsovA4f1VH9r9RXS3gZWVwACchwAAmLrmFW6HEOYXcKD9zYE',
	'Angry_Crack_Knuckles': 'CAACAgUAAx0CeySiRQACgdhpMtTmaaM_X3Wwj7mTqL1QmMVMFgAC6RwAAnPcmVXfrmP7l3njPzYE',
	'Angry_Tch': 'CAACAgUAAx0CeySiRQACgdppMtT8VzO1sQVVdRqQYIBRkQABj7gAAo4ZAAJLyZFVw0fiJd37JFk2BA',
	'Arrival_Here_I_Come': 'AACAgUAAx0CeySiRQACgdxpMtULVNDLLCik3JVp41gdbKnKGwAC9xkAApMomVVtiqAen2sruTYE',
	'Awkward_Panic': 'CAACAgUAAx0CeySiRQACgd5pMtUhe3FenixqGl8qtySB8Vj-rAACSxgAAswBmFVUzPa2GvXyHDYE',
	'Awkward_Polite_Smile': 'CAACAgUAAx0CeySiRQACgeBpMtU0GmxkEgEG-IbXcmd4lj9EigACixoAAlvHmFXNdzWMkYiUdDYE',
	'Bath_Time_Steam': 'AACAgUAAx0CeySiRQACgeRpMtVS7PIMFupszSgmJDbjPhqbuwACzBkAApnamFXfk3K8n0QW7DYE',
	'Begging_For_Headpats': 'CAACAgUAAx0CeySiRQACgeZpMtVlqjdfT5WCWmLT_jof4KgKTAACkhwAAodpmVVXtC_RHGbk-jYE',
	'Bored_Grazing': 'CAACAgUAAx0CeySiRQACgehpMtV3c99JAl9EbFrpn7c4tgMvqgACkBkAAm5wmFVJpnyJH0vH7zYE',
	'Brain_Buffering_Loading': 'AACAgUAAx0CeySiRQACgeppMtWNbxSzm-qibBmFIFP29S7CfQACexoAAoO7kFVxX8_Sm6bAdDYE',
	'Busy_Working': 'CAACAgUAAx0CeySiRQACgexpMtWev4n1gvKnzCibm5B8oxkyLAACoR4AAhimkVX09aiG_-yVIjYE',
	'Calculating_Math_Overload': 'AACAgUAAx0CeySiRQACge5pMtWrh607XTM0neEJj3wvNEdFnwAC3xsAAqnfmVU45-CZuvcrbzYE',
	'Cannot_Understand': 'CAACAgUAAx0CeySiRQACgfBpMtW6rep2Uqpom36oqUtF67gNewACyhYAAoqjmFXHzqlBsedL4TYE',
	'Checking_Files': 'CAACAgUAAx0CeySiRQACgfJpMtXNQrtpMD72b7pl2yXXh2tl1QAC7hwAAoUBmVVIPvwB6NrnVDYE',
	'Confident_Smirk': 'CAACAgUAAx0CeySiRQACgfRpMtXchGZzPWPDvcG_6FlbavyvfAACeRkAAnspmFVMvJjwRR4H6DYE',
	'Crying_FeelingUnloved': 'CAACAgUAAx0CeySiRQACgfZpMtXu2cfKSBjcfzVII7HlAhkV5AACpBwAAmhymVVBBehU6S4AAUs2BA',
	'Crying_Tearfully': 'CAACAgUAAx0CeySiRQACgfhpMtYAASG81od6jNcL0x3V_OSKVV8AAkQZAALXzJhVs1vn0bYVGLU2BA',
	'Disgusted_Eww': 'CAACAgUAAx0CeySiRQACgmRpMtqBEeDVukV5xH1ZRrLBr-z2yQACvB4AAkyTmVUKhMFnE6lk3TYE',
	'Dont_Know_Shrug': 'CAACAgUAAx0CeySiRQACgfppMtYPF-sNVowQWAg1yRr82OJ8WgACmBoAApDqmFWFsJGfpXIKzjYE',
	'Drained_Exhausted': 'CAACAgUAAx0CeySiRQACgfxpMtYgYHI1HWN9knZvCOBCd8pJPAAC9RsAAjMAAZlVJL0wKwWuO502BA',
	'Drinking_Cola_Burp': 'CAACAgUAAx0CeySiRQACgf5pMtYtIxyGKIHq7g1i8Tf00kqOCgACUhkAAtkWmFWCvCU-lilkFTYE',
	'Drinking_Tea': 'CAACAgUAAx0CeySiRQACgclpMslKzaQHI5fFIVYqc_7me-AvcQAC7hwAAqX2kVXiy_nOiVnJiDYE',
	'Eating_Melon_Spectating': 'CAACAgUAAx0CeySiRQACggJpMtZIPDRoLtt9a26ksuZL785GTQACNRkAAvTWkVWRoAqzz4ktYjYE',
	'Explosion_Afro_Fail': 'AACAgUAAx0CeySiRQACggRpMtZgzhg6l6XAmq86-K7guRqPbgACDBkAArNQmVW0agj51bnCkTYE',
	'Extreme_Shock': 'CAACAgUAAx0CeySiRQACggZpMtZ2gijL_EpcMdlZbPEzztBxvQAC6BoAAqNbkFWUMbw3vmZ0QzYE',
	'Feeding_Ah': 'CAACAgUAAx0CeySiRQACgghpMtaGMggpoCTeC-biXgfjGaRGNAACthcAAs_JmFXVPKeGv5RrezYE',
	'Fleeing_On_Broom': 'CAACAgUAAx0CeySiRQACghBpMtcpjEIHf4SyVydqSw71RwAByasAApA0AALcGJlVaGfLZC0sF2Q2BA',
	'Gift_Present': 'CAACAgUAAx0CeySiRQACghJpMtc7JSGOff5sQcbtpLtHUKYviQACTR4AAjhPmFXspS7S3fbZ4jYE',
	'Good_Morning': 'CAACAgUAAx0CeySiRQACgg5pMtb8pYtYUF2zl_hCZbxcFEKpDwACLR0AAgiSmVVelvWgh0X_lTYE',
	'Happy_Birthday_Cake': 'CAACAgUAAx0CeySiRQACghRpMtdMoMjEkNDIHhKBn4LbwA_EKgAC0RgAAlVzmVUulcpaiwFS7TYE',
	'Happy_Sweet': 'CAACAgUAAx0CeySiRQACghZpMtdgR9gxm2nAzbOjC3WRm6qqVQACthsAAhbXmVW4Ro4sYZi5xDYE',
	'Heart_Sign': 'CAACAgUAAx0CeySiRQACggppMta3ZrHcr409uvNgG3sEJVAdzAACYhoAAua0mVVUwQwJgNUw0TYE',
	'Hmph_Pout': 'CAACAgUAAx0CeySiRQACghppMteWK7O9lZ3GLG4mqLVrclIr4QACFhsAAtPHkFWARH40AAGvij42BA',
	'Holding_Mouthful': 'CAACAgUAAx0CeySiRQACghxpMtekSyFs22K3z2Qcpnz1gf_pmwAC8hkAAh3ImVXOjnh-KpHgTTYE',
	'Hooray_Cheering': 'CAACAgUAAx0CeySiRQACgh5pMtez2dbMzmoWerniy3u1hYsAAfIAAhgbAAKVJ5lVETKTGDEhEy82BA',
	'Horny_Drool': 'CAACAgUAAx0CeySiRQACgiBpMtfq-Js7idLDH5VqJUTXwnodggAClBoAAkfZmVXNZIGDms9XEjYE',
	'Hugging_Recharging': 'CAACAgUAAx0CeySiRQACgiJpMtgHB831c0Ga4R6im6AyWdRvBQACDRsAAqKbmFWHlVVspGLQWjYE',
	'In_Battle_Gaming': 'CAACAgUAAx0CeySiRQACgiRpMtgY6lqifyGcuVsjylQvJ5wr3AACsB0AAsHRmVVw2uQUK9LUnzYE',
	'Is_That_All_Scoff': 'CAACAgUAAx0CeySiRQACgiZpMtgn0RV1n8_WLjrdguOOxEl_OwACxiIAAorOmFXXvYn5d1iHizYE',
	'Kamen_Rider_Transform': 'CAACAgUAAx0CeySiRQACgiZpMtgn0RV1n8_WLjrdguOOxEl_OwACxiIAAorOmFXXvYn5d1iHizYE',
	'LMAO_Table_Slam': 'CAACAgUAAx0CeySiRQACgiZpMtgn0RV1n8_WLjrdguOOxEl_OwACxiIAAorOmFXXvYn5d1iHizYE',
	'Love_You_Pose': 'CAACAgUAAx0CeySiRQACgixpMthhMTFAJ5eEN3fmSEGbjXiJkQAC0RgAAoZTkFWHiSI-Aty0KTYE',
	'Maid_Service': 'CAACAgUAAx0CeySiRQACgi5pMthxDW9q3dTozz_xUE_PSYHkiwACzRkAAsTKmVVHy6toq-eRrzYE',
	'Meal_Ready_Excited': 'CAACAgUAAx0CeySiRQACgjBpMtiMe1rnGzo8OHp1evT21zBihwACUxwAAo4SkVWJVokrHTrdszYE',
	'Missing_You': 'CAACAgUAAx0CeySiRQACgjJpMtifqHwNcc9AuuScfBKbf0CYFQACXxwAAjN0mVVEUyK6hzq7cDYE',
	'No_DAME': 'CAACAgUAAx0CeySiRQACgjRpMtjGSkF2spXPaILdCL_CYodlYgACch0AAvqEmVVaw1UXBiGh8DYE',
	'No_Lewd_Bonk': 'CAACAgUAAx0CeySiRQACgjZpMtjgUEtkSk1nsOOZxZrqOZvmgwACxxoAAsdqmFUnl9bjBdDc4TYE',
	'Not_Interested': 'CAACAgUAAx0CeySiRQACgjhpMtjw5Lzy2Ucm2K3AU-oc-XVtWgAC-B0AAnFAmVXBdWnJUko-AjYE',
	'OK_Received': 'CAACAgUAAx0CeySiRQACgjppMtkH_SeegXC1UwnahebfO4ib8wACOB0AAny6mFU41GI9L8zSBjYE',
	'Out_Of_Power': 'CAACAgUAAx0CeySiRQACgjxpMtkWnliOdJRNZ9BXJFy9tHfm-QAC3xgAAuRamVX8QlOIcuQi0zYE',
	'Overwhelmed_Crash': 'CAACAgUAAx0CeySiRQACgj5pMtkmpTteJ6QHgzOI5e4vF6wRLgACmBwAAhhPmFU3U2eF4WIoRTYE',
	'Panic_Coding_Urgent': 'CAACAgUAAx0CeySiRQACgkBpMtkz7_WHxULIOYF9etK_nQNSzgACvxgAAvbimFU0k6yX2z9DdTYE',
	'Pat_Head': 'CAACAgUAAx0CeySiRQACgkJpMtlAv6G-B_DNVtl_COj7bC5nMAACRxoAAvIKmVUfHspjBQABH-M2BA',
	'Plan_Success': 'CAACAgUAAx0CeySiRQACgkRpMtlMTwyXpIptGeev39Pm_nugKwACBRsAAhIqmFWTSbZtvLWwKDYE',
	'Praise_Me_Work': 'CAACAgUAAx0CeySiRQACgkZpMtliFK2NhYskVlycMbJZ8bQ_lgACGBoAAgVomFX_xUOL_-zlqDYE',
	'Problem_Not_Big_Fire': 'CAACAgUAAx0CeySiRQACgkhpMtlywGyn8CPwo1JWe7nY9I2gMgAC7SEAApXpmVXq85cypKluujYE',
	'Reaction_Too_Lewd': 'CAACAgUAAx0CeySiRQACgkppMtmCsR_Np5lVm33MfFygGx48rAACdBwAAlQcmVUdaSdoygGIKzYE',
	'Really_Doubt': 'CAACAgUAAx0CeySiRQACgkxpMtmSk8BMNysMM5_tLZ6HWoO-pAAC9hoAAu0hmFVFaMH9yyFVoTYE',
	'Refuse_Listen': 'CAACAgUAAx0CeySiRQACgk5pMtmrYVRiFVmmV3WTsaXOvUSk5gACiRgAAqzxkFVqUclxLxK81jYE',
	'Refuse_X': 'CAACAgUAAx0CeySiRQACglBpMtm8CC-6V6QpujmbJq_aM9OtHQACliYAAomemVU9mP_WrxudejYE',
	'Reject_Dame_Cross': 'CAACAgUAAx0CeySiRQACglJpMtnMPA10ckIfz7OEwviN1NmWggACnCwAAhHbmVW2NVRlgQKDHjYE',
	'Roger_Salute': 'CAACAgUAAx0CeySiRQACglRpMtnZUkPkmD11zgHsVk7CGBnItQACYRYAAplUmFV7vNQiaAHZOTYE',
	'Running_Away_Bye': 'CAACAgUAAx0CeySiRQACglZpMtnptmWI95juvlnSyOZuaCq96wAC5xkAAqpPmVVR2kpHgmbc1jYE',
	'Scoff_Contempt': 'CAACAgUAAx0CeySiRQACglhpMtn6Tv_wWDKGPFtVFPfnRJIRhAACfh0AAry7mVU6FNTed0NO9zYE',
	'Secret_Observation_Box': 'CAACAgUAAx0CeySiRQACglppMtoRMjKxuG4jH7ihFJg-F-2FmQACHBoAAr9UmFWa7xMQSXleRDYE',
	'Secret_Observation': 'CAACAgUAAx0CeySiRQACglxpMtoxHl5_5vXiu_e0hI_FWvzOPAACWxcAAqZSmFWXY5o1oxfpdDYE',
	'Shocked_Question': 'CAACAgUAAx0CeySiRQACgl5pMtpDpI7YujXUNgzHN-xbyA9u7wACTRUAAlKRmVXlxsQ1J_SAhjYE',
	'Shy_Hesitation': 'CAACAgUAAx0CeySiRQACgmBpMtpSBkN09i_aQaJTTZEkTUVUygACLBwAApztmVWWYYliODiJgTYE',
	'Sleeping': 'CAACAgUAAx0CeySiRQACgmZpMtqkz4XtPIhphAnw-uH2Tc-2KAACtR0AAleymFUF3py6AVmZjDYE',
	'Speechless_Crows': 'CAACAgUAAx0CeySiRQACgmhpMtqypZdzFrAoITme3pfa_gqGJwACYhkAAq8kmFXCA3_U_qiiPjYE',
	'Standby_Mode': 'CAACAgUAAx0CeySiRQACgmppMtrEcHRDyZyW7WTYwJ6R64DtggACcRoAAjQKmFUpnLKb3kn1RTYE',
	'Surrender': 'CAACAgUAAx0CeySiRQACgmxpMtrRZrmhik-hzyNw6sSNf8G9_gACWhsAAu0nkFW4ejISmjeLAjYE',
	'System_Shutdown_Sleep': 'CAACAgUAAx0CeySiRQACgm5pMtre6ChjpaPABxTpFqxFzXoKcAACMBoAAgtSmVWHVwUb-owidjYE',
	'Taunt_Is_That_All': 'CAACAgUAAx0CeySiRQACgnBpMtr9VKz2pVs4npStwW8oBqw_rgACSBsAAobJmFUTDBYS4xKBxjYE',
	'Taunt_Noob_Weak': 'CAACAgUAAx0CeySiRQACgnJpMtsMAVNJd_vu1PYnQM2xI4W-1AACkB0AAu2wmVVCC0dtisSimTYE',
	'Teleport_PassingBy': 'CAACAgUAAx0CeySiRQACgnRpMtsb755ysl4dPRUCyu31DKH0SgACVBkAAnD5kFXIdy5X8rag5zYE',
	'Tell_Me_More_Sparkle': 'CAACAgUAAx0CeySiRQACgnZpMtsqhay3ZRFWqmcTBw2SgVgN-gACdhsAAvkBmVVa9igOQr_fZDYE',
	'Treating_You_Rich': 'CAACAgUAAx0CeySiRQACgb9pMrzu36TH4WWXClkiocZhAAGPxYUAAjcYAAKN_ZhVr9zmg3383Xg2BA',
	'Under_Control_Squeeze': 'CAACAgUAAx0CeySiRQACgnxpMtuyd2p-jG6GZZGYWqk_8vEy6gACXB4AAs39mFXdddSGTJBxBDYE',
	'Very_Happy': 'CAACAgUAAx0CeySiRQACgn5pMtu_WHfLmBDhOUBqfKX6fRisggACrhsAAlIxmVWhIBZ3qPtWTjYE',
	'Well_Behaved': 'CAACAgUAAx0CeySiRQACgoBpMtvLGWtumh7VwBnMTKNGuZXy6wACLBkAAvE4mVWC2TCU-_8SAzYE',
	'Yandere_Scissors_Who': 'CAACAgUAAx0CeySiRQACgoJpMtvYmOy1cGcqJXJegViseWAsiQAC5h4AAjqxkVXkEZTvM3vs6DYE',
}

/**
 * 获取贴纸的 Telegram 表情符号。
 * @param {string} sticker - 贴纸名称。
 * @returns {string} - Telegram 表情符号字符串。
 */
export function getTelegramSticker(sticker) {
	return `<:${stickerNameToFileId[sticker]}:GentianAphrodite:${sticker}>`
}
