name: Test Running

permissions:
  contents: read
  actions: write

on:
  workflow_dispatch:
  push:
    paths:
      - '**.mjs'
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  test-running:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: steve02081504/fount-charCI@master
        with:
          CI-filepath: .github/workflows/CI.mjs
